"""A figure the engine emits, and what kind of figure it is.

``governance.py`` used to hand out dollar and percentage figures as bare
``int`` values -- the ordinary-course threshold, an approval percentage --
computed from coefficients nobody chose and rendered into a memo as if they
were advice. Provenance recorded that the *position* was a starting point
(``Basis`` on the ``Recommendation``), but nothing stopped the specific
*number* inside that position from reading like a researched figure. A reader
sees "contracts above $40,000", not "a figure generated by multiplying your
capital by a coefficient nobody chose".

:class:`DerivedNumber` closes that gap for the numbers that flow through it.
Every one is exactly one of three states, and a reader (or a document
assembler) can always tell which:

* ``stated`` -- a person supplied or confirmed this value. Usable without
  qualification.
* ``proposed`` -- the system computed a starting point and shows the rule
  that produced it. Never a settled term.
* ``unresolved`` -- no basis exists yet; carries no value at all.

This is a different concept from :data:`tessera_os.governance.Basis`, which
records whether a *position* is a Tessera standard. A ``DerivedNumber`` never
carries a ``Basis`` -- the number underneath a scaffold position can still be
confirmed by a person without the position itself becoming a Tessera
standard, and conflating the two would let a confirmed number masquerade as
an adopted firm position, or vice versa.

Confirmation is a recorded act, not a checkbox: :class:`NumberConfirmationStore`
persists who confirmed which figure, for which project, and when -- the same
shape as the adoption ledger, and for the same reason. A figure in a client's
operating agreement should be traceable to a human who accepted it, and it
should survive a restart, which is why it lives in the same kind of durable
SQLite store as the review queue rather than in memory.
"""

from __future__ import annotations

import sqlite3
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field, model_validator

from .sqlite_store import connect as sqlite_connect

NumberState = Literal["stated", "proposed", "unresolved"]

# The labels governance.py uses to key confirmations. Shared here so the
# engine and the confirmation store never drift apart on a typo'd string.
ORDINARY_COURSE_THRESHOLD_LABEL = "ordinary-course threshold"
APPROVAL_THRESHOLD_LABEL = "approval threshold"


class DerivedNumber(BaseModel):
    """A single figure, tagged with which of the three D1 states it is in."""

    label: str = Field(min_length=1)
    value: int | None
    state: NumberState
    derivation: str = ""
    confirmed_by: str = ""
    confirmed_at: datetime | None = None

    @model_validator(mode="after")
    def _state_is_internally_consistent(self) -> DerivedNumber:
        if self.state == "proposed" and not self.derivation.strip():
            raise ValueError("a proposed DerivedNumber must carry its derivation")
        if self.state == "unresolved" and self.value is not None:
            raise ValueError("an unresolved DerivedNumber must not carry a value")
        if self.state != "unresolved" and self.value is None:
            raise ValueError(f"a {self.state} DerivedNumber must carry a value")
        if self.confirmed_by and self.state != "stated":
            raise ValueError("confirmed_by requires state == 'stated'")
        if bool(self.confirmed_by) != (self.confirmed_at is not None):
            raise ValueError("confirmed_by and confirmed_at must be set together")
        return self

    def render_inline(self, *, fmt) -> str:
        """Render this number inside a sentence, honestly marking its state.

        ``fmt`` turns the raw ``value`` into its displayed form (a dollar
        figure, a percentage) -- the caller knows which, this method only
        knows the state.
        """
        if self.state == "unresolved":
            return "an amount not yet determined (see open questions)"
        rendered = fmt(self.value)
        if self.state == "proposed":
            return f"{rendered} (proposed, not yet confirmed)"
        if self.confirmed_by:
            return f"{rendered} (confirmed by {self.confirmed_by})"
        return rendered


class DerivedNumberConfirmation(BaseModel):
    """One recorded confirmation: this figure, this value, this person, this moment."""

    label: str = Field(min_length=1)
    value: int
    confirmed_by: str = Field(min_length=1)
    confirmed_at: datetime


class NumberConfirmationStore:
    """Durable, per-project record of confirmed figures.

    Opened through :func:`tessera_os.sqlite_store.connect` for the same
    reason as the review queue and the artifact store: production runs this
    on an Azure Files SMB share, where SQLite's default locking assumptions
    do not hold. See ``sqlite_store.py`` for what that fixes.
    """

    def __init__(self, path: Path | str = "tessera-number-confirmations.db") -> None:
        self.path = str(path)
        with self._connect() as connection:
            connection.execute("""CREATE TABLE IF NOT EXISTS number_confirmations (
                tenant_id TEXT NOT NULL, project_id TEXT NOT NULL, label TEXT NOT NULL,
                value INTEGER NOT NULL, confirmed_by TEXT NOT NULL, confirmed_at TEXT NOT NULL,
                PRIMARY KEY (tenant_id, project_id, label))""")

    def _connect(self) -> sqlite3.Connection:
        return sqlite_connect(self.path)

    def confirm(self, *, tenant_id: str, project_id: str, label: str, value: int,
                confirmed_by: str, confirmed_at: datetime | None = None
                ) -> DerivedNumberConfirmation:
        confirmation = DerivedNumberConfirmation(
            label=label, value=value, confirmed_by=confirmed_by,
            confirmed_at=confirmed_at or datetime.now(UTC))
        with self._connect() as connection:
            connection.execute(
                """INSERT INTO number_confirmations
                   (tenant_id, project_id, label, value, confirmed_by, confirmed_at)
                   VALUES (?, ?, ?, ?, ?, ?)
                   ON CONFLICT (tenant_id, project_id, label)
                   DO UPDATE SET value = excluded.value, confirmed_by = excluded.confirmed_by,
                                 confirmed_at = excluded.confirmed_at""",
                (tenant_id, project_id, label, confirmation.value, confirmation.confirmed_by,
                 confirmation.confirmed_at.isoformat()))
        return confirmation

    def for_project(self, *, tenant_id: str,
                     project_id: str) -> dict[str, DerivedNumberConfirmation]:
        with self._connect() as connection:
            rows = connection.execute(
                "SELECT * FROM number_confirmations WHERE tenant_id = ? AND project_id = ?",
                (tenant_id, project_id)).fetchall()
        return {row["label"]: DerivedNumberConfirmation(
                    label=row["label"], value=row["value"], confirmed_by=row["confirmed_by"],
                    confirmed_at=datetime.fromisoformat(row["confirmed_at"]))
                for row in rows}
